import ProductImage from './ProductImage';
import { useState } from 'react';
import { Link, useOutletContext } from 'react-router-dom';
import { exportCsv } from './api';
import { Badge, Button, Card, DataTable, EmptyState, SearchInput, StatCard } from './components';
import { CatalogChart, CategoryDistribution } from './charts';
import Icon from './icons';
import { resolveImageUrl } from '../lib/api';

const orderColumns = [
  { key: 'id', label: 'Order ID' }, { key: 'customer', label: 'Customer' }, { key: 'items', label: 'Items' },
  { key: 'date', label: 'Date & time' }, { key: 'total', label: 'Order total', numeric: true },
  { key: 'payment', label: 'Payment' }, { key: 'fulfillment', label: 'Fulfillment' }, { key: 'tracking', label: 'Carrier / tracking' },
];
export default function Overview() {
  const { data, reload, busy, live, setLive, notify } = useOutletContext();
  const [range, setRange] = useState('Last 30d');
  const [chart, setChart] = useState('revenue');
  const [search, setSearch] = useState('');
  const [orderTab, setOrderTab] = useState('All Orders');
  const topProducts = [...data.products].sort((a, b) => b.salesCount - a.salesCount).slice(0, 4);
  const exportOverview = () => {
    exportCsv('store-overview.csv', ['Metric', 'Value', 'Scope'], [
      ['Products', data.catalog.count, 'Current catalog'], ['Categories', data.catalog.categories.length, 'Current catalog'],
      ['Catalog sales count', data.catalog.salesCount, 'Lifetime catalog metadata; no transaction history'],
      ['Revenue', 'Unavailable', range], ['Orders', 'Unavailable', range], ['Customers', 'Unavailable', 'No customer service'],
    ]); notify('Overview exported.');
  };
  return <div className="ad-stack">
    <section className="ad-page-heading"><div><div className="ad-title-row"><h1>Store Overview &amp; Live Operations</h1><Badge tone="success" dot>Catalog Online</Badge></div><p>Commerce insights and catalog visibility for your Rafay.com store.</p></div><div className="ad-overview-actions"><div className="ad-segmented" aria-label="Reporting period">{['Today', 'Yesterday', 'Last 7d', 'Last 30d', 'Last 90d'].map((item) => <button key={item} className={range === item ? 'ad-selected' : ''} aria-pressed={range === item} onClick={() => setRange(item)}>{item}</button>)}<Icon name="calendar" size={14} /></div><div className="ad-toolbar"><span className="ad-currency">USD ($)</span><Button icon="download" onClick={exportOverview}>Export</Button><Button icon="refresh" disabled={busy} onClick={() => reload()} aria-label="Refresh dashboard" /><Button primary icon="bolt" aria-pressed={live} onClick={() => setLive(!live)}>{live ? 'Live: 30s' : 'Live View'}</Button></div></div></section>
    <section className="ad-metrics"><div className="ad-stat-grid"><StatCard label="Total net revenue" value="—" detail="Sales revenue not available" footer={<><span>{range}</span><Badge>Not connected</Badge></>} icon="wallet" /><StatCard label="Total orders" value="—" detail="No order service connected" footer={<><span>Action backlog</span><span>— pending</span></>} icon="bag" /><StatCard label="Average order" value="—" detail="Order history not available" footer={<><span>Basket insights</span><span>—</span></>} icon="chart" /><StatCard label="Conversion rate" value="—" detail="Visitor analytics not connected" footer={<><span>Checkout abandonment</span><span>—</span></>} icon="chart" /></div><div className="ad-mini-grid"><Card className="ad-mini-stat"><Icon name="users" /><div><span>Total customers</span><strong>— <small>Not connected</small></strong></div></Card><Card className="ad-mini-stat"><Icon name="box" /><div><span>Catalog products</span><strong>{data.catalog.count.toLocaleString()} <small>items</small></strong></div><Badge tone="success">Available</Badge></Card><Card className="ad-mini-stat"><Icon name="alert" /><div><span>Pending action items</span><strong>— <small>No operations feed</small></strong></div></Card><Card className="ad-mini-stat"><Icon name="returns" /><div><span>Refund volume</span><strong>— <small>Not connected</small></strong></div></Card></div></section>
    <div className="ad-analytics-grid"><Card title={chart === 'revenue' ? 'Revenue, Orders & Gross Profit Trends' : 'Catalog Growth & Product History'} subtitle={chart === 'revenue' ? `Reporting period: ${range}. Sales history is not connected.` : 'Product creation dates from your existing catalog.'} className="ad-trends" action={<div className="ad-segmented"><button className={chart === 'revenue' ? 'ad-selected' : ''} aria-pressed={chart === 'revenue'} onClick={() => setChart('revenue')}>Revenue</button><button className={chart === 'catalog' ? 'ad-selected' : ''} aria-pressed={chart === 'catalog'} onClick={() => setChart('catalog')}>Catalog</button></div>}>
      {chart === 'catalog' ? <CatalogChart products={data.products} /> : <><div className="ad-revenue-empty"><div className="ad-chart-grid" aria-hidden="true">{[1,2,3,4].map((i) => <span key={i} />)}</div><EmptyState icon="chart" title="Your sales story starts here" description="Revenue and profit trends will appear when order and payment history is connected." action={<Button icon="chart" onClick={() => setChart('catalog')}>Explore catalog insights</Button>} /></div><div className="ad-chart-footnote"><span><i className="ad-legend-dot" />Net revenue</span><span><i className="ad-legend-dot ad-green" />Gross profit</span><span className="ad-muted">Transaction history unavailable</span></div></>}
    </Card><CategoryDistribution products={data.products} /></div>
    <div className="ad-operations-grid"><Card title="Order Pipeline & Fulfillment Pulse" subtitle="A single view of your order and fulfillment stages." action={<Link className="ad-text-link" to="/admin/shipping">View shipments <Icon name="arrow" size={13} /></Link>} className="ad-pipeline"><div className="ad-pipeline-grid">{[['Pending Review', 'help'], ['Payment Confirmed', 'check'], ['Pick & Pack', 'box'], ['Shipped / Transit', 'truck'], ['Delivered', 'check'], ['Refund / Returns', 'returns']].map(([label, icon]) => <div className="ad-pipeline-stage" key={label}><span>{label}<Icon name={icon} size={13} /></span><strong>—</strong><small>No connected orders</small></div>)}</div><div className="ad-panel-note"><Icon name="help" size={15} /><span>Fulfillment reporting is waiting for an order service.</span><Link to="/admin/orders" className="ad-text-link">View orders</Link></div></Card>
    <Card title="Stock Health & Catalog" action={<Link className="ad-text-link" to="/admin/products/inventory">Inventory</Link>} subtitle="Stock quantities are not tracked in the current catalog." className="ad-stock"><div className="ad-stock-items">{topProducts.map((product) => <Link className="ad-stock-item" key={product.id} to={`/admin/products?q=${encodeURIComponent(product.name)}`}><ProductImage src={resolveImageUrl(product.image)} alt="" loading="lazy" /><div><strong>{product.name}</strong><small>ID: {product.id} · {product.category}</small></div><Badge>Stock —</Badge></Link>)}</div><div className="ad-stock-footer"><span>{data.catalog.count} products in your catalog</span><Link className="ad-button ad-primary" to="/admin/products">View catalog</Link></div></Card></div>
    <Card title="Recent Orders" subtitle="The latest transactions from your store." action={<Button icon="filter" onClick={() => notify('Order filters will become available when order history is connected.')}>Filters</Button>} className="ad-orders-card"><div className="ad-orders-toolbar"><div className="ad-order-tabs">{['All Orders', 'Unfulfilled', 'Paid', 'Fraud Risk', 'Returns'].map((tab) => <button key={tab} className={orderTab === tab ? 'ad-selected' : ''} aria-pressed={orderTab === tab} onClick={() => setOrderTab(tab)}>{tab} <span>—</span></button>)}</div><SearchInput label="Search orders" placeholder="Search by order ID, customer, email…" value={search} onChange={setSearch} /></div><DataTable columns={orderColumns} rows={[]} emptyTitle={search ? 'No orders match this search' : 'No order history connected'} emptyDescription="Your store does not yet provide order records. Transactions will appear here when available." /><div className="ad-table-footer"><span>Order records unavailable</span><Link className="ad-text-link" to="/admin/orders">Open orders <Icon name="arrow" size={13} /></Link></div></Card>
  </div>;
}
