import { useState } from 'react';
import { Link, useOutletContext } from 'react-router-dom';
import { Badge, Button, Card, DataTable, EmptyState, SearchInput, StatCard } from './components';
import { CatalogChart, CategoryDistribution } from './charts';
import { exportCsv } from './api';
import Icon from './icons';

const modules = {
  orders: { title: 'Orders', subtitle: 'Track customer orders from payment through delivery.', icon: 'bag', columns: ['Order ID', 'Customer', 'Date', 'Total', 'Payment', 'Fulfillment'], message: 'No order history connected', detail: 'Orders will appear here when your store supports order records.', filters: ['All orders', 'Unfulfilled', 'Paid', 'Returns'] },
  customers: { title: 'Customers', subtitle: 'A clear view of customer relationships and purchase history.', icon: 'users', columns: ['Customer', 'Email', 'Orders', 'Total spent', 'Last order'], message: 'Customer records are not connected', detail: 'Your store does not provide a centralized customer directory. Customer records will appear when one is available.', filters: ['All customers', 'Returning', 'New'] },
  payments: { title: 'Payments & Payouts', subtitle: 'Monitor transactions, payment status, and settlement activity.', icon: 'wallet', columns: ['Transaction', 'Order', 'Date', 'Amount', 'Method', 'Status'], message: 'No payment provider connected', detail: 'Payment and settlement records will appear when a payment service is available.', filters: ['All transactions', 'Captured', 'Pending', 'Refunded'] },
  returns: { title: 'Returns & Refunds', subtitle: 'Review returns and follow refund progress.', icon: 'returns', columns: ['Return ID', 'Order', 'Customer', 'Amount', 'Reason', 'Status'], message: 'No returns service connected', detail: 'Return requests and refunds will appear here when order returns are supported.', filters: ['All returns', 'Requested', 'Approved', 'Completed'] },
  shipping: { title: 'Shipping & Logistics', subtitle: 'Follow shipments from your store to your customers.', icon: 'truck', columns: ['Shipment', 'Order', 'Carrier', 'Tracking', 'Destination', 'Status'], message: 'No shipping service connected', detail: 'Shipments, tracking updates, and carrier information will appear when fulfillment is available.', filters: ['All shipments', 'Preparing', 'In transit', 'Delivered'] },
  taxes: { title: 'Taxes & Duties', subtitle: 'A consolidated view of tax and duty records.', icon: 'receipt', columns: ['Region', 'Tax type', 'Rate', 'Collected', 'Period'], message: 'Tax reporting is not connected', detail: 'Tax totals will appear when order tax records are available.', filters: ['All regions'] },
  marketing: { title: 'Marketing', subtitle: 'Keep track of campaigns and their performance.', icon: 'megaphone', columns: ['Campaign', 'Channel', 'Audience', 'Status', 'Results'], message: 'No marketing platform connected', detail: 'Campaign activity and attribution will appear when a marketing service is available.', filters: ['All campaigns', 'Active', 'Completed'] },
  apps: { title: 'Apps', subtitle: 'Services available to your merchant workspace.' },
  notifications: { title: 'Notifications', subtitle: 'Your latest store updates and operational alerts.' },
  'not-found': { title: 'Page not found', subtitle: 'This admin page does not exist.' },
};
export function ModulePage({ page }) {
  const config = modules[page];
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('');
  if (page === 'not-found') return <Card><EmptyState icon="help" title={config.title} action={<Link to="/admin" className="ad-button ad-primary">Back to dashboard</Link>} /></Card>;
  return <div className="ad-stack"><section className="ad-page-heading"><div><h1>{config.title}</h1><p>{config.subtitle}</p></div><Badge>{page === 'apps' ? '1 available' : 'No activity feed'}</Badge></section>
    {page === 'apps' ? <div className="ad-app-grid"><Card title="Storefront Catalog" action={<Badge tone="success" dot>Connected</Badge>}><div className="ad-app-icon"><Icon name="box" size={28} /></div><p>Your existing store products, categories, prices, and rating summaries are available in this workspace.</p><Link className="ad-button" to="/admin/products">Browse catalog <Icon name="arrow" size={14} /></Link></Card><Card title="Commerce services"><EmptyState icon="puzzle" compact title="Additional services are not connected" description="Orders, payments, shipping, and marketing will appear when these services are available." /></Card></div> : page === 'notifications' ? <Card><EmptyState icon="bell" title="No notification feed connected" description="Operational alerts will appear when your store provides an activity feed." /></Card> : <><div className="ad-notice"><Icon name="help" size={17} /><span>{config.detail}</span></div><Card className="ad-orders-card"><div className="ad-table-toolbar"><div className="ad-order-tabs">{config.filters.map((value, index) => <button key={value} aria-pressed={filter ? filter === value : index === 0} className={(filter ? filter === value : index === 0) ? 'ad-selected' : ''} onClick={() => setFilter(value)}>{value}</button>)}</div><SearchInput value={search} onChange={setSearch} label={`Search ${config.title.toLowerCase()}`} placeholder={`Search ${config.title.toLowerCase()}…`} /></div><DataTable columns={config.columns.map((label) => ({ key: label, label }))} rows={[]} emptyTitle={search ? 'No results match your search' : config.message} emptyDescription={config.detail} /><div className="ad-table-footer">Records unavailable</div></Card></>}
  </div>;
}
export function Categories() {
  const { data } = useOutletContext();
  const [search, setSearch] = useState('');
  const categories = data.catalog.categories.filter((name) => name.includes(search.toLowerCase()));
  return <div className="ad-stack"><section className="ad-page-heading"><div><h1>Categories</h1><p>The product groups in your existing storefront catalog.</p></div><SearchInput value={search} onChange={setSearch} label="Search categories" placeholder="Search categories…" /></section><div className="ad-category-grid">{categories.map((name) => {
    const products = data.products.filter((product) => product.category === name);
    return <Card key={name} className="ad-category-card"><div className="ad-category-icon"><Icon name="box" size={24} /></div><h2 className="ad-capitalize">{name}</h2><p>{products.length} products</p><div className="ad-category-prices"><span>Price range</span><strong>${Math.min(...products.map((p) => p.price))} – ${Math.max(...products.map((p) => p.price))}</strong></div><Link className="ad-button" to={`/admin/products?category=${encodeURIComponent(name)}`}>View products <Icon name="arrow" size={14} /></Link></Card>;
  })}</div>{!categories.length && <Card><EmptyState title="No categories found" description="Try a different search." /></Card>}</div>;
}
export function Analytics() {
  const { data, notify } = useOutletContext();
  const exportAnalytics = () => {
    exportCsv('catalog-analytics.csv', ['Category', 'Products', 'Catalog sales count', 'Catalog review count'], data.catalog.categories.map((category) => {
      const products = data.products.filter((product) => product.category === category);
      return [category, products.length, products.reduce((sum, p) => sum + p.salesCount, 0), products.reduce((sum, p) => sum + p.reviews, 0)];
    })); notify('Catalog analytics exported.');
  };
  return <div className="ad-stack"><section className="ad-page-heading"><div><h1>Analytics &amp; BI</h1><p>Understand your catalog with the data available today.</p></div><Button icon="download" onClick={exportAnalytics}>Export report</Button></section><div className="ad-stat-grid"><StatCard label="Catalog products" value={data.catalog.count} detail="All current catalog items" footer="Current catalog" icon="box" /><StatCard label="Catalog sales count" value={data.catalog.salesCount.toLocaleString()} detail="Lifetime product metadata" footer="No dated transaction history" /><StatCard label="Average rating" value={data.catalog.averageRating.toFixed(2)} detail="Unweighted product average / 5" footer="Current catalog" icon="star" /><StatCard label="Catalog reviews" value={data.catalog.reviewCount.toLocaleString()} detail="Combined product review counts" footer="Individual reviews unavailable" icon="users" /></div><div className="ad-analytics-grid"><Card title="Catalog Growth & Product History" subtitle="Products grouped by their recorded creation month."><CatalogChart products={data.products} /></Card><CategoryDistribution products={data.products} /></div><Card title="Sales Channels & Traffic" subtitle="Revenue attribution and visitor analytics"><EmptyState icon="chart" title="Sales and visitor analytics are not connected" description="Channel revenue, device traffic, conversion, and profit require transaction and visitor history." /></Card></div>;
}
export function Staff() {
  const { session } = useOutletContext();
  return <div className="ad-stack"><section className="ad-page-heading"><div><h1>Staff &amp; Roles</h1><p>Workspace access and administrator permissions.</p></div><Badge>1 administrator</Badge></section><Card title="Workspace administrator" subtitle="Your store uses a dedicated administrator account."><DataTable columns={[{ key: 'name', label: 'Name' }, { key: 'email', label: 'Email' }, { key: 'role', label: 'Role', render: (row) => <Badge tone="success">{row.role}</Badge> }]} rows={[{ id: 'admin', ...session.admin }]} /></Card><Card title="Permissions"><div className="ad-permissions">{[['View catalog & categories', true], ['Export catalog reports', true], ['View catalog analytics', true], ['Create or edit products', false], ['Manage orders & customers', false], ['Invite staff', false]].map(([label, enabled]) => <div key={label}><Icon name={enabled ? 'check' : 'lock'} size={17} /><span>{label}</span><Badge tone={enabled ? 'success' : 'neutral'}>{enabled ? 'Available' : 'Not enabled'}</Badge></div>)}</div></Card></div>;
}
export function Settings() {
  const { session, live, setLive, onLogout, logoutPending } = useOutletContext();
  return <div className="ad-stack"><section className="ad-page-heading"><div><h1>Settings</h1><p>Your store, workspace preferences, and current session.</p></div></section><div className="ad-settings-grid"><Card title="Store profile" subtitle="Your connected storefront"><dl className="ad-settings-list"><div><dt>Store name</dt><dd>Rafay.com</dd></div><div><dt>Currency</dt><dd>USD · US Dollar</dd></div><div><dt>Catalog</dt><dd><Badge tone="success" dot>Connected</Badge></dd></div></dl><Link to="/" target="_blank" rel="noreferrer" className="ad-button">Visit storefront <Icon name="arrow" size={14} /></Link></Card><Card title="Administrator" subtitle="Your current workspace account"><dl className="ad-settings-list"><div><dt>Name</dt><dd>{session.admin.name}</dd></div><div><dt>Email</dt><dd>{session.admin.email}</dd></div><div><dt>Role</dt><dd>{session.admin.role}</dd></div></dl></Card><Card title="Workspace preferences" subtitle="Refresh behavior for this visit"><div className="ad-setting-row"><div><strong>Live catalog updates</strong><p>Refresh the catalog every 30 seconds while this tab is visible.</p></div><button className={`ad-switch ${live ? 'ad-switch-on' : ''}`} type="button" role="switch" aria-checked={live} aria-label="Live catalog updates" onClick={() => setLive(!live)}><span /></button></div></Card><Card title="Session & security" subtitle="Your administrator access"><dl className="ad-settings-list"><div><dt>Session status</dt><dd><Badge tone="success">Active</Badge></dd></div><div><dt>Expires</dt><dd>{new Date(session.expiresAt).toLocaleString()}</dd></div></dl><Button icon="logout" onClick={onLogout} disabled={logoutPending}>{logoutPending ? 'Signing out…' : 'Logout'}</Button></Card></div></div>;
}
